version: '3'
services:
  api:
    build: .
    ports:
      - "9000:9000"
    command: npm run dev
    networks:
      - net
    environment:
      - MONGO_URI=skurl-mongo:27017/mydb
    depends_on:
      - mongo
    restart: unless-stopped
    container_name: skurl-api
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - net
    restart: unless-stopped
    container_name: skurl-mongo
secrets:
  mongo_uri:
    external: true
networks:
  net:
    driver: bridge
volumes:
  mongodata: